
build: HashTable_WithStandardKeys.o

HashTable_WithStandardKeys.o : HashTable_WithStandardKeys.cc HashTable_WithStandardKeys.h
	$(CC) $(OPTFLAGS) $(CFLAGS) HashTable_WithStandardKeys.cc

clean:
	rm -f *.o *.gch
